### ISSUE TITLE
Support additional check types

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-monit#3]
Did you have plans for supporting different check types? How did you plan on handling it? I was looking at putting alerts for the system to check available space, but there's no easy work around it since you need a pid.

**Comment by drybjed** [comment]
Monit is used on the individual hosts, I would rather prefer to focus on something more centralized. Currently you can use LibreNMS with DebOps, in the future I'll try to integrate [check_mk](https://github.com/debops-contrib/ansible-checkmk_agent) with the project which LibreNMS can use to monitor remote hosts.

As for Monit, I suspect that its role will diminish somewhat since `systemd` can be configured to restart services on failure... Actually in the beginning `debops.monit` was supposed to be included in the `common.yml` playbook (ie. configured by default), but after some deliberation with @nickjj we reversed that decision, since most of the software on a host "just works" when everything is fine and doesn't require constant monitoring. And if something is crashing now and then it's better to fix the issue rather than use a bandaid.

I don't really use `debops.monit` anywhere. I guess it has its use when you have a single host, but when more than a couple is involved, it's better to use more suitable tools. I expected the potential `debops.monit` users to configure the various services as the need arises and `debops.monit` to just be a convenient way to do it.

So right now, there are no plans to expand the role, but if you have some nice ideas, shoot. :)

**Comment by carlalexander** [comment]
Oh I see! Let me look at LibreNMS :wink:

**Comment by drybjed** [comment]
The role now uses YAML text blocks to define Monit configuration, therefore the issue no longer applies; I'm closing it.
